### ISSUE TITLE
Node 10 incompatibility

### ISSUE THREAD

**Issue by christianbundy** [blockades/patchbay-dark-crystal#12]
This repo currently depends on an old version of ssb-private which depends on leveldown@1.7.2, which isn't compatible with Node 10.

**Comment by KGibb8** [comment]
Thanks @christianbundy for noting this. It was developed in `v8.4.0`. We'll be bringing it up to date soon.

**Comment by KGibb8** [comment]
As far as I can see, this is an issue for `ssb-private` as we're up to date with the latest version `0.2.3` as specified on [npm](https://www.npmjs.com/package/ssb-private).
