### ISSUE TITLE
Avatar size is crazy big!?

### ISSUE THREAD

**Issue by KGibb8** [blockades/patchbay-dark-crystal#17]
![screenshot from 2018-10-19 14-32-56](https://user-images.githubusercontent.com/17786217/47221387-15e58880-d3ac-11e8-987c-77f03bcfb485.png)

**Comment by ameba23** [comment]
im seeing this too.  im guessing because of styling changes in patchbay?

**Comment by dan-mi-sun** [comment]
This has been fixed as per ssb convo here: %9NjpIKb9YvfIQFxrhO0p6iOatbTTfeebp68a4M/7wqU=.sha256
